---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  document-end:
    present: false
  document-start:
    present: false
