---
data_dir: /var/data

core:
  hostname: coreos
  user:
    # docker run -it --rm quay.io/coreos/mkpasswd --method=yescrypt
    password:
  ssh_authorized_keys: []

docker:
  internal_network_name: internal
  external_network_name: external
  loki:
    url: https://<username>:<password>@<hostname>/loki/api/v1/push
    batch_size: 128
  user:
    # docker run -it --rm quay.io/coreos/mkpasswd --method=yescrypt
    password:
    uid: 1001  # docker
    gid: 100  # users
  ssh_authorized_keys: []

# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
cloudflared:
  token:
