---
data_dir: /var/data

core:
  hostname: coreos
  sshd_port: 22  # https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
  user:
    # docker run -it --rm quay.io/coreos/mkpasswd --method=yescrypt
    password:
  ssh_authorized_keys: []
  root_password:

docker:
  internal_network_name: internal
  external_network_name: external
  loki:
    url: https://<username>:<password>@<hostname>/loki/api/v1/push
    batch_size: 128
  user:
    # docker run -it --rm quay.io/coreos/mkpasswd --method=yescrypt
    password:
    uid: 1001  # docker
    gid: 100  # users
  ssh_authorized_keys: []

# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
cloudflared:
  token:
