systemd:
  units:

    # Change default `podman` to `docker`, due to Portainer
    - name: docker.service
      enabled: true
    - name: podman.service
      mask: true

    - name: configure-docker.service
      enabled: true
      contents: |-2
        [Unit]
        After=setup-docker-user.service
        Requires=docker.service network.target network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=0
        ExecStart=/usr/local/sbin/configure-docker.sh
        ExecStartPost=/usr/bin/systemctl restart docker.service

        [Install]
        WantedBy=multi-user.target

storage:
  files:
    - path: /etc/docker/daemon.json
      mode: !!str 0774
      user: {name: docker}
      group: {name: users}
      contents:
        inline: "{}"
    - path: /etc/sysconfig/docker
      overwrite: true
      contents:
        inline: |2
          # /etc/sysconfig/docker
          OPTIONS="--selinux-enabled \
            --live-restore \
            --default-ulimit nofile=1024:1024 \
            --init-path /usr/libexec/docker/docker-init \
            --userland-proxy-path /usr/libexec/docker/docker-proxy \
          "

    - path: /usr/local/sbin/configure-docker.sh
      mode: !!str 0544
      user: {name: docker}
      group: {name: users}
      contents:
        inline: |2
          {% filter indent(10) -%}
          {% include "files/configure-docker.sh" %}
          {%- endfilter %}
